[package]
name = "ray_tracer"
version = "0.1.0"
authors = ["Luc Bergeron <bergeronl@college-montreal.qc.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geefr-ppm = "0.2.0"